name: game_domain
description: Domain classes for the game.
version: 0.1.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dev_dependencies:
  build_runner: ^2.4.8
  mocktail: ^1.0.0
  test: ^1.19.2
  very_good_analysis: ^5.1.0

dependencies:
  equatable: ^2.0.5
  json_annotation: ^4.8.1