name: api_client
description: Client to access the api.
version: 0.1.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dev_dependencies:
  mocktail: ^1.0.0
  test: ^1.19.2
  very_good_analysis: ^6.0.0

dependencies:
  equatable: ^2.0.5
  game_domain:
    path: ../../api/packages/game_domain
  http: ^1.2.1
