name: hint_repository
description: A repository to handle the hints.
version: 0.1.0+1
publish_to: none

environment:
  sdk: "^3.3.0"

dependencies:
  db_client:
    path: ../db_client
  game_domain:
    path: ../game_domain
  google_generative_ai: ^0.3.1

dev_dependencies:
  mocktail: ^1.0.3
  test: ^1.25.2
  very_good_analysis: ^5.1.0
