name: backend_admin
description: A desktop application to perform admin operations in the backend
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.4.0 <4.0.0"
  flutter: ">=3.22.0"

dependencies:
  bloc: ^8.1.3
  crossword_repository:
    path: ../packages/crossword_repository
  db_client:
    path: ../packages/db_client
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.4
  flutter_localizations:
    sdk: flutter
  game_domain:
    path: ../packages/game_domain
  http: ^1.2.1
  intl: ^0.19.0

dev_dependencies:
  bloc_test: ^9.1.6
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.3
  very_good_analysis: ^6.0.0

flutter:
  uses-material-design: true
  generate: true
