name: board_uploader
description: Crossword board uploader.
version: 0.1.0+1
publish_to: none

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  built_collection: ^5.1.1
  built_value: ^8.9.1
  characters: ^1.3.0
  collection: ^1.18.0
  csv: ^6.0.0
  dart_firebase_admin: ^0.3.0
  game_domain:
    path: ../../api/packages/game_domain

dev_dependencies:
  build_runner: ^2.4.8
  built_value_generator: ^8.9.1
  mocktail: ^1.0.3
  test: ^1.25.2
  very_good_analysis: ^5.1.0