name: authentication_repository
description: Repository to manage authentication.
version: 0.1.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.19.0"

dependencies:
  equatable: ^2.0.5
  firebase_auth: ^4.19.1
  firebase_core: ^2.29.0
  firebase_core_platform_interface: ^5.0.0
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.1.8
  rxdart: ^0.27.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.3
  very_good_analysis: ^6.0.0
