name: board_renderer
description: Renders the board in images
version: 0.1.0+1
publish_to: none

environment:
  sdk: "^3.3.0"

dependencies:
  game_domain:
    path: ../game_domain
  http: ^1.2.1
  image: ^4.1.7

dev_dependencies:
  mocktail: ^1.0.3
  test: ^1.25.2
  very_good_analysis: ^5.1.0
