// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAHWxa8wFh90H1PBioYjH8cjXT3LYXYwzE',
    appId: '1:550787969847:web:afe8b194e8d91ae52360b2',
    messagingSenderId: '550787969847',
    projectId: 'io-crossword-dev',
    authDomain: 'io-crossword-dev.firebaseapp.com',
    storageBucket: 'io-crossword-dev.appspot.com',
    measurementId: 'G-Z7N512KKE3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA3OuzoQoQkgO81JCvH2Wl6fDxcV_Ur3iE',
    appId: '1:550787969847:android:ef2648020296849f2360b2',
    messagingSenderId: '550787969847',
    projectId: 'io-crossword-dev',
    storageBucket: 'io-crossword-dev.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBTKzfYL_1kkmf2lvZ0QfIh6ZzhrAUQeFw',
    appId: '1:550787969847:ios:1d0c38ded7a13ae72360b2',
    messagingSenderId: '550787969847',
    projectId: 'io-crossword-dev',
    storageBucket: 'io-crossword-dev.appspot.com',
    iosBundleId: 'com.example.verygoodcore.io-crossword',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBTKzfYL_1kkmf2lvZ0QfIh6ZzhrAUQeFw',
    appId: '1:550787969847:ios:9d5fec9bc706127d2360b2',
    messagingSenderId: '550787969847',
    projectId: 'io-crossword-dev',
    storageBucket: 'io-crossword-dev.appspot.com',
    iosBundleId: 'com.example.myApp.RunnerTests',
  );
}
