name: jwt_middleware
description: A dart_frog middleware for checking JWT authorization.
version: 0.1.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  clock: ^1.1.1
  dart_frog: ^1.1.0
  equatable: ^2.0.5
  http: ^1.2.1
  jose: ^0.3.4
  x509: ^0.2.4+2

dev_dependencies:
  mocktail: ^1.0.0
  test: ^1.19.2
  very_good_analysis: ^6.0.0
