/// Flutter icons IoIcons
/// Copyright (C) 2024 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  IoIcons
///      fonts:
///       - asset: fonts/IoIcons.ttf
///
///
///
import 'package:flutter/widgets.dart';

class IoIcons {
  IoIcons._();

  static const _kFontFam = 'IoIcons';
  static const String? _kFontPkg = 'io_crossword_ui';

  static const IconData gemini =
      IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
