name: app_ui
description: UI Toolkit for the IO Crossword Flutter Application.
version: 0.1.0+1
publish_to: none

environment:
  sdk: ^3.3.0
  flutter: ^3.19.0

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.3
  very_good_analysis: ^5.1.0
