name: firebase_cloud_storage
description: A package to manage a firebase bucket.
version: 0.1.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  grpc: ^3.1.0
  http: ^1.2.1

dev_dependencies:
  mocktail: ^0.3.0
  test: ^1.19.2
  very_good_analysis: ^3.1.0
