name: crossword_repository
description: Repository to manage the crossword.
version: 0.1.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  cloud_firestore: ^4.16.1
  game_domain:
    path: ../../api/packages/game_domain

dev_dependencies:
  fake_cloud_firestore: ^2.4.8
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.0
  test: ^1.19.2
  very_good_analysis: ^5.1.0
