name: api
description: I/O Crossword API
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  board_renderer:
    path: packages/board_renderer
  clock: ^1.1.1
  collection: ^1.18.0
  crossword_repository:
    path: packages/crossword_repository
  dart_frog: ^1.1.0
  db_client:
    path: packages/db_client
  firebase_cloud_storage:
    path: packages/firebase_cloud_storage
  game_domain:
    path: packages/game_domain
  google_cloud: ^0.2.0
  hint_repository:
    path: packages/hint_repository
  jwt_middleware:
    path: packages/jwt_middleware
  leaderboard_repository:
    path: packages/leaderboard_repository
  logging: ^1.2.0
  shelf_cors_headers: ^0.1.5

dev_dependencies:
  mocktail: ^1.0.3
  test: ^1.19.2
  very_good_analysis: ^6.0.0
