name: api
description: I/O Crossword API
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  dart_frog: ^1.1.0
  game_domain:
    path: packages/game_domain
  leaderboard_repository:
    path: packages/leaderboard_repository

dev_dependencies:
  mocktail: ^1.0.0
  test: ^1.19.2
  very_good_analysis: ^5.1.0
