name: backend_admin

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  pull_request:
    paths:
      - "api/backend_admin/**"
      - ".github/workflows/backend_admin.yaml"
    branches:
      - main

jobs:
  build:
    uses: VeryGoodOpenSource/very_good_workflows/.github/workflows/flutter_package.yml@v1
    with:
      dart_sdk: stable
      working_directory: api/backend_admin
      min_coverage: 0
