name: board_uploader

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  pull_request:
    paths:
      - "packages/board_uploader/**"
      - ".github/workflows/board_uploader.yaml"
    branches:
      - main

jobs:
  build:
    uses: VeryGoodOpenSource/very_good_workflows/.github/workflows/dart_package.yml@v1
    with:
      dart_sdk: stable
      working_directory: packages/board_uploader
      coverage_excludes: "**/*.g.dart"
      min_coverage: 20
