name: deploy_app_prod

on: workflow_dispatch

env:
  CROSSWORD_URL: https://crossword.withgoogle.com

jobs:
  deploy-dev:
    runs-on: ubuntu-latest
    name: Deploy App Production
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          channel: beta
          flutter-version: 3.23.0-0.1.pre
      - run: flutter packages get
      - run: flutter build web -t lib/main_production.dart --dart-define CROSSWORD_URL=${{ env.CROSSWORD_URL }} --dart-define RECAPTCHA_KEY=${{ secrets.RECAPTCHA_KEY_PROD }} --wasm


      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT_PROD }}"
          projectId: io-crossword
          target: app_prod
          expires: 30d
          channelId: live
