name: deploy_app_staging

on: workflow_dispatch

env:
  CROSSWORD_URL: https://stg-e7b2896c65fabc0480edc6c0e.web.app

jobs:
  deploy-dev:
    runs-on: ubuntu-latest
    name: Deploy App Staging
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          channel: beta
          flutter-version: 3.23.0-0.1.pre
      - run: flutter packages get
      - run: flutter build web -t lib/main_staging.dart --dart-define CROSSWORD_URL=${{ env.CROSSWORD_URL }} --dart-define RECAPTCHA_KEY=${{ secrets.RECAPTCHA_KEY }} --wasm


      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT_DEV }}"
          projectId: io-crossword-dev
          target: app_stg
          expires: 30d
          channelId: live
