name: deploy_app_dev

on:
  push:
    branches:
      - main
      - feat/add-landing-page

env:
  CROSSWORD_URL: https://e7b2896c65fabc0480edc6c0e.web.app

jobs:
  deploy-dev:
    runs-on: ubuntu-latest
    name: Deploy App Development
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js runtime environment
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'

      - name: Build landing page
        run: |
          cd landing
          yarn install
          yarn build
          cd ..

      - uses: subosito/flutter-action@v2
        with:
          channel: beta
          flutter-version: 3.23.0-0.1.pre
      - run: flutter packages get
      - run: flutter build web -t lib/main_development.dart --dart-define CROSSWORD_URL=${{ env.CROSSWORD_URL }} --dart-define RECAPTCHA_KEY=${{ secrets.RECAPTCHA_KEY }} --wasm

      - name: Move build files to public folder
        run: |
          mkdir public
          mkdir public/game
          mv build/web/index.html public/game/
          mv build/web/{.,}* public/
          mv landing/dist/index.html public/
          mv landing/dist/assets/* public/assets/

      - name: Deploy landing page and game to Firebase Hosting
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT_DEV }}"
          projectId: io-crossword-dev
          target: app_dev
          expires: 30d
          channelId: live
